Numpy

In [55]:
import numpy as np
print(np.array([1, 2, 3, 4]))

[1 2 3 4]


In [56]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

ARRAY CREATION :-CONVERSION FROM OTHER PYTHON STRUCTURES

In [57]:
listarray = np.array([[7,5,6],[7,5,9]])
listarray

array([[7, 5, 6],
       [7, 5, 9]])

In [58]:
listarray.shape

(2, 3)

In [59]:
listarray.size

6

In [60]:
listarray.strides

(12, 4)

In [61]:
listarray.__array_struct__

<capsule object NULL at 0x0000023659A2CA80>

INTRINSIC NUMPY ARRAY CREATION

In [62]:
zeros = np.zeros((2,5))

In [63]:
zeros.dtype

dtype('float64')

In [64]:
zeros.shape

(2, 5)

In [65]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [66]:
rng  = np.arange(15)

In [67]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [68]:
lspace = np.linspace(1,5,4)

In [69]:
lspace      #numbers is between 1 and 5 ang 4 is digit howmany digit inclde

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [70]:
emp = np.empty((4,6))

In [71]:
emp         #give random value between 4 and 6

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.86921822e-306, 1.42413555e-306, 1.78019082e-306],
       [1.37959740e-306, 6.23057349e-307, 1.02360935e-306,
        1.69120416e-306, 1.78022342e-306, 6.23058028e-307],
       [1.06811422e-306, 9.45699680e-308, 1.11258854e-306,
        1.11261502e-306, 1.42410839e-306, 7.56597770e-307],
       [6.23059726e-307, 1.42419530e-306, 9.79101761e-307,
        9.34601642e-307, 1.60219035e-306, 2.56765117e-312]])

In [72]:
emp_like = np.empty_like(lspace)

In [73]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [74]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [75]:
ide = np.identity(45)

In [76]:
ide


array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [77]:
ide.shape

(45, 45)

In [78]:
arr = np.arange(99)

In [79]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [80]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [81]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [82]:
ar = np.array(x)

In [83]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [84]:
ar.sum(axis=0)

array([12,  8,  9])

In [85]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [86]:
ar.T          #replec row and column

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [87]:
ar.flat

In [88]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [89]:
ar.ndim #dimension of array

2

In [90]:
ar.nbytes

36

In [91]:
one = np.array([1,5,445,879,576])

In [92]:
one.argmax()     #give index where maximun elemement

3

In [93]:
one.argmax(axis=0)

3

In [94]:
one.argsort()

array([0, 1, 2, 4, 3], dtype=int64)

In [95]:
one.argmin()

0

In [96]:
ar = np.array([[1,6,8],[9,8,7],[0,5,1]])

In [97]:
ar

array([[1, 6, 8],
       [9, 8, 7],
       [0, 5, 1]])

In [98]:
ar2 = np.array([[7,8,6],[9,23,5],[99,67,4]])

In [99]:
ar2

array([[ 7,  8,  6],
       [ 9, 23,  5],
       [99, 67,  4]])

In [100]:
ar + ar2

array([[ 8, 14, 14],
       [18, 31, 12],
       [99, 72,  5]])

In [101]:
ar * ar2

array([[  7,  48,  48],
       [ 81, 184,  35],
       [  0, 335,   4]])

In [102]:
np.sqrt(ar)

array([[1.        , 2.44948974, 2.82842712],
       [3.        , 2.82842712, 2.64575131],
       [0.        , 2.23606798, 1.        ]])

In [103]:
np.where(ar>5)

(array([0, 0, 1, 1, 1], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))

In [104]:
np.count_nonzero(ar)

8

In [105]:
ary1 = np.array([[1,2,3]])
print(ary1)

[[1 2 3]]


In [110]:
h1 = np.append(ary1,[[10,11,14]],axis=0)
print(h1)

[[ 1  2  3]
 [10 11 14]]
